#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080
# Setting user in config by replacing '#user' and its value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# Replacing port 80 with 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# Giving read and write permission to the config file to owner
chmod 644 /etc/nginx/nginx.conf
# apache might interfer with nginx if its still running so has to be killed
pkill apache2
# Starting the nginx service with the new nginx user
sudo -u nginx service nginx start
